platformName android
automationName uiautomator2
deviceName vivo V70 FE
udid adb-10BG4M2A040041S-TDpYgf._adb-tls-connect._tcp

appPackage industrybuying.com.industrybuying
appActivity industrybuying.com.industrybuying.MainActivity
